### ISSUE TITLE
谢谢您的贡献！有几个建议。

### ISSUE THREAD

**Issue by YNCao** [ustctug/ustcbeamer#3]
1. 结尾致谢页面的模板缺失
2. 文档说明能否详细一些? 比如调整字体更换主题等细节问题。
3.

**Comment by ArthurZz** [comment]
感谢反馈，我近期会抽空完善以下内容：
- 完善文档说明；
- 添加一些可供选择的字体主题；
- 致谢页面由于各人对式样的要求各不相同，众口难调，不过我依然会添加一个参考式样。
