### ISSUE TITLE
some error about EOL

### ISSUE THREAD

**Issue by Freed-Wu** [ustctug/ustcbeamer#5]
in `main.tex`, there are some EOLs are `<CR><LF>` while other EOLs are `<LF>`. the former is the EOL of Windows OS, and the latter is the EOL of Unix/Linux/Mac OS X. it results in the file will be thinked as a Unix file, but at the end of some lines there will exist some `<CR>`. like this.

![Screenshot from 2020-07-24 12-12-18](https://user-images.githubusercontent.com/32936898/88359939-01b39400-cda7-11ea-9afe-1d0b6c52549f.png)

0x0d is the ascii code of `<CR>`.

it is not a serious problem, because of the `<CR>` always exist after the '%', which means the begin of a comment.

and perhaps there are other problems in this beamer... still, it is a good work.
thanks for your effort in this beamer.

**Comment by ArthurZz** [comment]
谢谢，之前还真没意识到这个问题，我一般使用的是 Win 平台的 VS Code，默认的 EOL 是 `<LF>`；这个问题可能是因为该项目其他贡献人添加注释的时候用的是 `<CR>`。谢谢！以后我们会注意该问题。
