### ISSUE TITLE
an advice about the logos

### ISSUE THREAD

**Issue by Freed-Wu** [ustctug/ustcbeamer#6]
I notice this beamer dependent on some figures(e.g. ustc_logo.pdf). in fact, there is a package named cnlogo which can output the most logos of Chinese universities. perhaps we can leverage this package to reduce the dependency of these figures.
<https://www.latexstudio.net/archives/51714.html>
<https://github.com/yuxtech/cnlogo>

**Comment by ArthurZz** [comment]
谢谢您提供的方法！先前并不知道有 inkscape 这么方便的工具，所以一直使用的是[中国科大视觉识别](http://lswhw.ustc.edu.cn/index.php/index/lists/011)提供的矢量图。我会抽空将背景和封面转化成  tikz 代码，不过考虑到使用者可能遇到编译问题，依然会保留一份带图片的版本。
